--- #YAML:1.0
name:                Parse-RPN
version:             2.41
abstract:            Parse::RPN Is a minimalist RPN parser/processor (a little like FORTH)
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
