--- #YAML:1.0
name:                Parse-RPN
version:             2.35
abstract:            Parse::RPN Is a minimalist RPN parser/processor (a little like FORTH)
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
